name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [x86_64]

    steps:
      # 0️⃣ 检出仓库（若只编译 protobuf 可省略，但通常保留）
      - uses: actions/checkout@v4

      # 1️⃣ 安装依赖
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build zip curl perl pkg-config libclang-dev musl-tools git

      # 2️⃣ 下载并解压 protobuf-31.1
      - name: Download protobuf source
        run: |
          curl -L -o protobuf.tar.gz https://github.com/protocolbuffers/protobuf/releases/download/v31.1/protobuf-31.1.tar.gz
          tar -xzf protobuf.tar.gz

      # 3️⃣ 配置、构建、安装
      - name: Configure & build protobuf
        working-directory: ./protobuf-31.1
        run: |
          mkdir -p build "${GITHUB_WORKSPACE}/install"
          cd build
          cmake .. \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/install"
          cmake --build . -j
          cmake --install .

      # 4️⃣ 打包 install 目录
      - name: Package install directory
        working-directory: ${{ github.workspace }}
        run: |
          zip -r build-linux-${{ matrix.target }}.zip install

      # 5️⃣ 上传产物
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: protobuf-build-linux-${{ matrix.target }}
          path: build-linux-${{ matrix.target }}.zip
          retention-days: 1
